version: "3"
services:
  app:
    container_name: "mysqlcontainer"
    build: .
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=jdbc:mysql://mysqldb:3306/codibdfacil
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=123456
    depends_on:
      - mysqldb

  mysqldb:
    container_name: "mysqldb"
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=codigobdfacil
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456

volumes:
  mysql-data:
    external: false
