spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#AWS Credntials
aws.access.key = ${ACCESS_KEY}
aws.secret.key = ${SECRET_KEY}

#mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ganapp2024@gmail.com
spring.mail.password=sihr qzso afwq ykhm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.thymeleaf.enabled=false
spring.jpa.open-in-view=false

#spring.mvc.static-path-pattern=/uploads/**
#spring.resources.static-locations=file:uploads/
